# Site settings
title: Dream Eutopia 
SEOTitle: eutopia的博客 | Dream Eutopia 
header-img: img/home-bg.jpg
email: 18058563573@163.com
description: "这里是 @eutopia 的个人博客，与你一起发现更大的世界 | 生而无畏。战至终章"
keyword: "eutopia, eutopia, dreameutopia, 鬼栈, dreameutopia, @hdreameutopia, eutopia的博客, Dream Eutopia, 博客, 个人网站, 互联网, Web, JavaScript, React, React Native, 前端, 设计"
url: "https://dreameutopia.github.io/" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'eutopia/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: DreamEutopia
zhihu_username: DreamEutopia
github_username: dreameutopia
twitter_username: dreameutopia
facebook_username:  dreameutopia
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: dreameutopia

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: dreameutopia.cn

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "要做一个有 dream 的程序员 <br>     From:eutopiaplace"
#sidebar-avatar: https://github.com/Huxpro.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "通义千问", href: "https://qianwen.aliyun.com/" },
    { title: "豆包", href: "https://www.doubao.com/chat/" },
    { title: "KiMi", href: "https://kimi.moonshot.cn/" },
    { title: "天工", href: "https://www.tiangong.cn/" },
    { title: "notdiamond自动匹配大模型", href: "https://chat.notdiamond.ai/" },
    { title: "liblib 绘画ai", href: "https://www.liblib.art/" },
    { title: "Chatgpt镜像站", href: "https://chat2.oaichat.cc/" },
    { title: "Chatgpt备用镜像站", href: " https://chat.tinycms.xyz:3002/" },
  ]
